version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command: start-dev
  app_dev:
    image: node:alpine
    container_name: app_dev_test
    working_dir: /app
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./app/:/app
    command: npm run code

